; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.14"

; Modules
projects[admin_menu][subdir] = "sites/all/modules/contrib/admin_menu"
projects[admin_menu][version] = "3.0-rc3"

projects[advanced_help][subdir] = "sites/all/modules/contrib/advanced_help"
projects[advanced_help][version] = "1.0"

projects[auto_nodetitle][subdir] = "sites/all/modules/contrib/auto_nodetitle"
projects[auto_nodetitle][version] = "1.0"

projects[better_formats][subdir] = "sites/all/modules/contrib/better_formats"
projects[better_formats][version] = "1.x-dev"

projects[ctools][subdir] = "sites/all/modules/contrib/ctools"
projects[ctools][version] = "1.0"

projects[date][subdir] = "sites/all/modules/contrib/date"
projects[date][version] = "2.5"

projects[db_maintenance][subdir] = "sites/all/modules/contrib/db_maintenance"
projects[db_maintenance][version] = "1.1"

projects[diff][subdir] = "sites/all/modules/contrib/diff"
projects[diff][version] = "2.0"

projects[disable_messages][subdir] = "sites/all/modules/contrib/disable_messages"
projects[disable_messages][version] = "1.0"

projects[entity][subdir] = "sites/all/modules/contrib/entity"
projects[entity][version] = "1.0-rc3"

projects[features][subdir] = "sites/all/modules/contrib/features"
projects[features][version] = "1.0-rc3"

projects[field_group][subdir] = "sites/all/modules/contrib/field_group"
projects[field_group][version] = "1.1"

projects[fieldset_helper][subdir] = "sites/all/modules/contrib/fieldset_helper"
projects[fieldset_helper][version] = "2.1"

projects[pathauto][subdir] = "sites/all/modules/contrib/pathauto"
projects[pathauto][version] = "1.1"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[ref_txn][download][type] = ""
projects[ref_txn][download][url] = ""
projects[ref_txn][type] = "module"
projects[ref_txn][subdir] = "sites/all/modules/custom/ref_txn"
projects[ref_txn][version] = "1.0-alpha1"

projects[taxonomy_manager][subdir] = "sites/all/modules/contrib/taxonomy_manager"
projects[taxonomy_manager][version] = "1.0-beta3"

projects[token][subdir] = "sites/all/modules/contrib/token"
projects[token][version] = "1.1"

projects[views][subdir] = "sites/all/modules/contrib/views"
projects[views][version] = "3.3"

projects[views_data_export][subdir] = "sites/all/modules/contrib/views_data_export"
projects[views_data_export][version] = "3.0-beta6"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[webauth][download][type] = ""
projects[webauth][download][url] = ""
projects[webauth][type] = "module"
projects[webauth][version] = "3.0"

; Themes
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[acquia_marina][download][type] = ""
projects[acquia_marina][download][url] = ""
projects[acquia_marina][type] = "theme"
projects[acquia_marina][version] = "0.1-alpha1"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[fusion][download][type] = ""
projects[fusion][download][url] = ""
projects[fusion][type] = "theme"
projects[fusion][subdir] = "sites/all/themes"
projects[fusion][version] = "1.0-alpha1"

; Modules
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[datetweaks][download][type] = ""
projects[datetweaks][download][url] = ""
projects[datetweaks][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[refstats][download][type] = ""
projects[refstats][download][url] = ""
projects[refstats][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[reverse_proxy][download][type] = ""
projects[reverse_proxy][download][url] = ""
projects[reverse_proxy][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[ref][download][type] = ""
projects[ref][download][url] = ""
projects[ref][type] = "theme"

