; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.14"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc3"

projects[advanced_help][subdir] = "contrib"
projects[advanced_help][version] = "1.0"

projects[auto_nodetitle][subdir] = "contrib"
projects[auto_nodetitle][version] = "1.0"

projects[better_formats][subdir] = "contrib"
projects[better_formats][version] = "1.x-dev"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.0"

projects[date][subdir] = "contrib"
projects[date][version] = "2.5"

projects[disable_messages][subdir] = "contrib"
projects[disable_messages][version] = "1.0"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.0-rc3"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0-rc3"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

projects[fieldset_helper][subdir] = "contrib"
projects[fieldset_helper][version] = "2.1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.1"

; Reference transaction Feature
projects[ref_txn][type] = "module"
projects[ref_txn][subdir] = "custom"
projects[ref_txn][download][type] = "git"
projects[ref_txn][download][url] = "git@github.com:jbickar/ref_txn.git"
projects[ref_txn][download][tag] = "7.x-1.0-alpha2"

projects[taxonomy_manager][subdir] = "contrib"
projects[taxonomy_manager][version] = "1.0-beta3"

projects[token][subdir] = "contrib"
projects[token][version] = "1.1"

projects[views][subdir] = "contrib"
projects[views][version] = "3.3"

projects[views_data_export][subdir] = "contrib"
projects[views_data_export][version] = "3.0-beta6"

projects[refstats][download][type] = "git"
projects[refstats][download][url] = "git@github.com:jbickar/refstats.git"
projects[refstats][type] = "module"

; Themes
projects[ref][download][type] = "git"
projects[ref][download][url] = "git@github.com:jbickar/ref.git"
projects[ref][type] = "theme"

; Profile
projects[refstats_profile][type] = "profile"
projects[refstats_profile][download][type] = "git"
projects[refstats_profile][download][url] = "git@github.com:jbickar/refstats_profile.git"
projects[refstats_profile][download][branch] = 7.x-1.x
